# Generated by Django 4.2.3 on 2023-07-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='description',
            new_name='bio',
        ),
    ]
