# Generated by Django 4.2.3 on 2023-07-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_born_date_author_date_born'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='born_location',
            new_name='location_born',
        ),
    ]
